# Generated by Django 5.0.2 on 2025-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='thumbnil',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='category',
            field=models.CharField(choices=[('Most Popular', 'mostpopular'), ('Comedy', 'comedy'), ('News', 'news'), ('Crime', 'crime'), ('Sports', 'sports')], default='-1', max_length=50),
        ),
    ]
