# Generated by Django 5.0.2 on 2025-04-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_rename_thumbnil_podcast_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='category',
            field=models.CharField(choices=[('Most Popular', 'mostpopular'), ('Comedy', 'comedy'), ('News', 'news'), ('Crime', 'crime'), ('Sports', 'sports'), ('Study', 'study')], default='-1', max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/'),
        ),
    ]
